export const GET_TOP_NEWS = "GET_TOP_NEWS";
export const GET_TOP_NEWS_START = "GET_TOP_NEWS_START";
export const GET_TOP_NEWS_SUCCESS = "GET_TOP_NEWS_SUCCESS";
export const GET_TOP_NEWS_ERROR = "GET_TOP_NEWS_ERROR";
export const GET_SELECTED_NEWS_START = "GET_SELECTED_NEWS_START";
export const GET_SELECTED_NEWS_SUCCESS = "GET_SELECTED_NEWS_SUCCESS";
export const GET_SELECTED_NEWS_ERROR = "GET_SELECTED_NEWS_ERROR";


