export default {
  //screen names
  SCREEN_LOGIN: "Login",
  SCREEN_SPLASH: "Splash",
  SCREEN_PERSONALDATAFILL: "PersonalDataFill",
  SCREEN_FORGETPASSWORD: "ForgetPassword",
  SCREEN_TERMSANDCONDITION: "TearmsAndConditions",
  SCREEN_MEDICALDATA: "MedicalDataScreen",
  SCREEN_CONCUSSIONSTARTPANEL: "ConcussionStartPanel",
  SCREEN_BASELINETESTSELSCREEN: "BaselineTestSelectionScreen",
  SCREEN_CONSUSSIONHISTORYQUSCREEN: "ConcussionHistoryQuScreen",
  SCREEN_CONCUSSIONSYMTOMSCREEN: "ConcussionSymptomsScreen",
  SCREEN_CONCUSSIONSTARTSCREEN: "ConcussionStartScreen",
  SCREEN_MYPROFILE: "MyProfileScreen",
  SCREEN_COGNITIVE_TEST_INTROSCREEN: "CognitiveTestIntroScreen",
  SCREEN_COGNITIVE_MEMORY_TEST_SCREEN: "CognitiveMemoryTestScreen",
  SCREEN_COGNITIVE_SYMBOL_TEST_SCREEN: "CognitiveSymbolTestScreen",
  SCREEN_COGNITIVE_ATTENTION_TESTSCREEN: "CognitiveAttentionTestScreen",
  SCREEN_COGNITIVE_PERFORMANCE_TESTSCREEN: "CognitivePerformanceTestScreen",
  SCREEN_COGNITIVE_DELAY_MEMORY_TESTSCREEN: "CognitiveDelayMemoryTestScreen",
  SCREEN_BASELINE_BUFFALOTREADMILL_TETSSCREEN: "BaselineBuffaloTreadmillTest",
  SCREEN_CONCUSSION_START_RECOVERY_FIRST: "ConcussionStartRecovery",

  BPANEL_LANDSCAPE_HEIGHT: 250,
  BPANEL_LANDSCAPE_LEFT: 40,
  BPANEL_LANDSCAPE_RIGHT: 40,



  COGNITIVE_TEST_START_WAITING_TIME:6000,
  COGNITIVE_TEST_ID: 2,
  COGNITIVE_TEST_VISUALMEMORY_ID: 2,
  TREADMILL_TEST_ID: 1,

  //
  COGNITIVE_TEST_STEP_INSTRUCTION:"0",
  COGNITIVE_TEST_STEP_FIRST_COUNTDOWN:"0.5",
  COGNITIVE_TEST_STEP_QUESTIONS:"1",
  COGNITIVE_TEST_STEP_WAITING_FOR_ANSWER:"2",
  COGNITIVE_TEST_STEP_SECOND_COUNTDOWN:"2.5",
  COGNITIVE_TEST_STEP_ANSWERS:"3",
  COGNITIVE_TEST_STEP_FINISH:"4",

  COGNITIVESYMBOLTEST_ASSET_FOLDER: "/symbolstestimages/"
};
